production:
  adapter: postgresql
  database: band_central_production

development:
  adapter: postgresql
  database: band_central_development

test:
  adapter: postgresql
  database: band_central_test
